import {API_KEY, AUTH_DOMAIN, DATABASE_URL, PROJECT_ID, STORAGE_BUCKET, MESSAGE_ID, APP_ID, MEASUREMENT_ID} from 'react-native-dotenv'

export default{
    API_KEY, AUTH_DOMAIN, DATABASE_URL, PROJECT_ID, STORAGE_BUCKET, MESSAGE_ID, APP_ID, MEASUREMENT_ID
}